#  Applied Data Science Capstone Project - The Battle of Neighborhoods

In this applied data science capstone project, two cities which are the top tourist destination in the world are explored. These cities are New York City, USA and Greater London, UK. The neighbourhoods of both cities are segmented and clustered. The ultimate goal of this project is to explore and get insight regarding which city is more eco- and vegan-friendly for health and environmental conscious travellers from all over the world. 

#### Import necessary libraries

In [1]:

import numpy as np  # library to handle data in a vectorized manner
import pandas as pd # library for data analsysis
import requests # library to handle requests


Waiting for a Spark session to start...
Spark Initialization Done! ApplicationId = app-20181024102125-0002


# New York City


#### Load census data of New York City from CSV file

In [2]:
!wget -O censusNYC.csv https://data.cityofnewyork.us/api/views/swpk-hqdp/rows.csv?accessType=DOWNLOAD
    
print("Data source downloaded")

--2018-10-24 10:21:27--  https://data.cityofnewyork.us/api/views/swpk-hqdp/rows.csv?accessType=DOWNLOAD
Resolving data.cityofnewyork.us (data.cityofnewyork.us)... 52.206.68.26, 52.206.140.199, 52.206.140.205
Connecting to data.cityofnewyork.us (data.cityofnewyork.us)|52.206.68.26|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/csv]
Saving to: 'censusNYC.csv'

censusNYC.csv           [ <=>                ]  18.58K  --.-KB/s    in 0s      

Last-modified header invalid -- time-stamp ignored.
2018-10-24 10:21:28 (199 MB/s) - 'censusNYC.csv' saved [19026]

Data source downloaded


In [3]:
# Create the dataframe consist of six columns: Borough, Year, FIPS County Code, NTA Code, NTA Name, and Population

df_NYC = pd.read_csv('censusNYC.csv')
df_NYC

Borough  Year  FIPS County Code NTA Code  \
0            Bronx  2000                 5     BX01   
1            Bronx  2000                 5     BX03   
2            Bronx  2000                 5     BX05   
3            Bronx  2000                 5     BX06   
4            Bronx  2000                 5     BX07   
5            Bronx  2000                 5     BX08   
6            Bronx  2000                 5     BX09   
7            Bronx  2000                 5     BX10   
8            Bronx  2000                 5     BX13   
9            Bronx  2000                 5     BX14   
10           Bronx  2000                 5     BX17   
11           Bronx  2000                 5     BX22   
12           Bronx  2000                 5     BX26   
13           Bronx  2000                 5     BX27   
14           Bronx  2000                 5     BX28   
15           Bronx  2000                 5     BX29   
16           Bronx  2000                 5     BX30   
17           Bronx  2000                 5     BX31   
18           Bronx  2000                 5     BX33   
19           Bronx  2000                 5     BX34   
20           Bronx  2000                 5     BX35   
21           Bronx  2000                 5     BX36   
22           Bronx  2000                 5     BX37   
23           Bronx  2000                 5     BX39   
24           Bronx  2000                 5     BX40   
25           Bronx  2000                 5     BX41   
26           Bronx  2000                 5     BX43   
27           Bronx  2000                 5     BX44   
28           Bronx  2000                 5     BX46   
29           Bronx  2000                 5     BX49   
..             ...   ...               ...      ...   
360         Queens  2010                81     QN61   
361         Queens  2010                81     QN62   
362         Queens  2010                81     QN63   
363         Queens  2010                81     QN66   
364         Queens  2010                81     QN68   
365         Queens  2010                81     QN70   
366         Queens  2010                81     QN71   
367         Queens  2010                81     QN72   
368         Queens  2010                81     QN76   
369         Queens  2010                81     QN98   
370         Queens  2010                81     QN99   
371  Staten Island  2010                85     SI01   
372  Staten Island  2010                85     SI05   
373  Staten Island  2010                85     SI07   
374  Staten Island  2010                85     SI08   
375  Staten Island  2010                85     SI11   
376  Staten Island  2010                85     SI12   
377  Staten Island  2010                85     SI14   
378  Staten Island  2010                85     SI22   
379  Staten Island  2010                85     SI24   
380  Staten Island  2010                85     SI25   
381  Staten Island  2010                85     SI28   
382  Staten Island  2010                85     SI32   
383  Staten Island  2010                85     SI35   
384  Staten Island  2010                85     SI36   
385  Staten Island  2010                85     SI37   
386  Staten Island  2010                85     SI45   
387  Staten Island  2010                85     SI48   
388  Staten Island  2010                85     SI54   
389  Staten Island  2010                85     SI99   

                                              NTA Name  Population  
0                                   Claremont-Bathgate       28149  
1                      Eastchester-Edenwald-Baychester       35422  
2                           Bedford Park-Fordham North       55329  
3                                              Belmont       25967  
4                                            Bronxdale       34309  
5                               West Farms-Bronx River       34542  
6      Soundview-Castle Hill-Clason Point-Harding Park       50753  
7                  Pelham Bay-Country Club-City 

In [4]:
# Explore the data type

df_NYC.dtypes

Borough             object
Year                 int64
FIPS County Code     int64
NTA Code            object
NTA Name            object
Population           int64
dtype: object

In [5]:
#  Change the data type of Year from intiger to string

df_NYC1 = df_NYC[["Year"]].astype(str)
df_NYC['Year'] = df_NYC1['Year'].values
df_NYC.head()

Borough  Year  FIPS County Code NTA Code                         NTA Name  \
0   Bronx  2000                 5     BX01               Claremont-Bathgate   
1   Bronx  2000                 5     BX03  Eastchester-Edenwald-Baychester   
2   Bronx  2000                 5     BX05       Bedford Park-Fordham North   
3   Bronx  2000                 5     BX06                          Belmont   
4   Bronx  2000                 5     BX07                        Bronxdale   

   Population  
0       28149  
1       35422  
2       55329  
3       25967  
4       34309

In [6]:
df_NYC.dtypes

Borough             object
Year                object
FIPS County Code     int64
NTA Code            object
NTA Name            object
Population           int64
dtype: object

In [7]:
# Create the dataframe for year 2010 that consist of six columns: Borough, Year, FIPS County Code, NTA Code, NTA Name, and Population

df_NYC1 = df_NYC[df_NYC.Year != '2000']
df_NYC1.head()

Borough  Year  FIPS County Code NTA Code                         NTA Name  \
195   Bronx  2010                 5     BX01               Claremont-Bathgate   
196   Bronx  2010                 5     BX03  Eastchester-Edenwald-Baychester   
197   Bronx  2010                 5     BX05       Bedford Park-Fordham North   
198   Bronx  2010                 5     BX06                          Belmont   
199   Bronx  2010                 5     BX07                        Bronxdale   

     Population  
195       31078  
196       34517  
197       54415  
198       27378  
199       35538

In [8]:
# Group by the dataframe by borough and form a new dataframe with two columns: Borough and Population

df_NYC2 = df_NYC1.groupby(by=['Borough'])['Population'].sum().reset_index()
df_NYC2.head()

Borough  Population
0          Bronx     1385108
1       Brooklyn     2504700
2      Manhattan     1585873
3         Queens     2230722
4  Staten Island      468730

In [9]:
# Compute the total number of Borough in New York City

No_Borough_NYC = len(df_NYC2.index)
print('Total Number of Borough:{}'.format (No_Borough_NYC))

Total Number of Borough:5


In [10]:
# Compute New York City's total population 

Total_Population_NYC = df_NYC2['Population'].sum()
print('Total Population of New York City is:{}'.format (Total_Population_NYC))

Total Population of New York City is:8175133


In [11]:
# Identify the Borough which has max population size in New York City
 
df_NYC2.loc[df_NYC2['Population'].idxmax()]

Borough       Brooklyn
Population     2504700
Name: 1, dtype: object

In [12]:
# Identify the Borough which has min population size in New York City
 
df_NYC2.loc[df_NYC2['Population'].idxmin()]

Borough       Staten Island
Population           468730
Name: 4, dtype: object

New York City has five boroughs. Among all borough called 'Brooklyn' has the highest population size of 2,504,700 wheras the borough named 'Staten Island' has the least population size which is 468,730.

## Visualize population of New York City in each borough 

In [13]:
# New York City latitude and longitude values

latitude =  40.730610
longitude = -73.935242

In [14]:
# download New York City geojson file

!wget --quiet   http://data.beta.nyc//dataset/68c0332f-c3bb-4a78-a0c1-32af515892d6/resource/7c164faa-4458-4ff2-9ef0-09db00b509ef/download/42c737fd496f4d6683bba25fb0e86e1dnycboroughboundaries.geojson -O NYC.json
    
print('GeoJSON file downloaded!')   

GeoJSON file downloaded!


#### Import necessary libraries to plot choropleth map

In [15]:
!conda install -c conda-forge folium=0.5.0 --yes
import folium

print('Folium installed and imported!')

Solving environment: done

# All requested packages already installed.

Folium installed and imported!


In [16]:
# create map and display it

NYC_geo = r'NYC.json' # geojson file

# create a plain world map
NYC_map = folium.Map(location=[latitude, longitude], zoom_start = 10)

# generate choropleth map using the total population of each borough in New York City 
NYC_map.choropleth(
    geo_data=NYC_geo,
    data=df_NYC2,
    columns=['Borough', 'Population'],
    key_on='feature.properties.borough',
    fill_color='YlOrRd', 
    fill_opacity=0.7, 
    line_opacity=0.2,
    legend_name='Population Size of New York City 2010'
)

# display map

NYC_map 

It can be noticed from the choropleth map that two broughts of New York City have high population (above 2.2 million).

# Greater London

 #### Import necessary libraries to import table from URL

In [17]:
from bs4 import BeautifulSoup

#### Import census data of London

In [18]:
# Create the dataframe consist of seven columns

URL ='https://www.citypopulation.de/php/uk-greaterlondon.php' 
Rq = requests.get(URL)
BS = BeautifulSoup(Rq.content,'lxml')
table = BS.find_all('table')[0] 
df = pd.read_html(str(table))[0]
df_GL = pd.DataFrame(df)
df_GL

Name   Status  PopulationEstimate1981-06-30  \
0     Barking and Dagenham  Borough                        161300   
1                   Barnet  Borough                        295200   
2                   Bexley  Borough                        217400   
3                    Brent  Borough                        248300   
4                  Bromley  Borough                        299200   
5                   Camden  Borough                        179100   
6           City of London     City                          6700   
7      City of Westminster  Borough                        188400   
8                  Croydon  Borough                        320700   
9                   Ealing  Borough                        285300   
10                 Enfield  Borough                        260900   
11               Greenwich  Borough                        214100   
12                 Hackney  Borough                        185200   
13  Hammersmith and Fulham  Borough                        150200   
14                Haringey  Borough                        206900   
15                  Harrow  Borough                        199900   
16                Havering  Borough                        242000   
17              Hillingdon  Borough                        233600   
18                Hounslow  Borough                        201000   
19               Islington  Borough                        165400   
20  Kensington and Chelsea  Borough                        141200   
21    Kingston upon Thames  Borough                        134400   
22                 Lambeth  Borough                        251700   
23                Lewisham  Borough                        237500   
24                  Merton  Borough                        167600   
25                  Newham  Borough                        211900   
26               Redbridge  Borough                        221800   
27    Richmond upon Thames  Borough                        164800   
28               Southwark  Borough                        218800   
29                  Sutton  Borough                        170200   
30           Tower Hamlets  Borough                        144700   
31          Waltham Forest  Borough                        217200   
32              Wandsworth  Borough                        262400   

    PopulationEstimate1991-06-30  PopulationEstimate2001-06-30  \
0                         155500                        165700   
1                         297700                        319500   
2                         218100                        218800   
3                         240800                        269600   
4                         293500                        296200   
5                         180700                        202600   
6                           5400                          7400   
7                         185000                        203300   
8                         315900                        335100   
9                         283800                        307300   
10                        260100                        277300   
11                        210900                        217500   
12                        185000                        207200   
13                        153800                        169400   
14                        207000                        221300   
15                        203000                        210000   
16                        230900                        224700   
17                        234400                        245600   
18                        203900                        216000   
19                        171800                        179400   
20                        143600                        162200   
21                        136100                        149000   
22                        255000                        273400   
23                        240200                        254300   
24                       

In [19]:
# Select name and the latest population 

df_GL1 = df_GL[['Name','PopulationEstimate2011-06-30']]
df_GL1.head()

Name  PopulationEstimate2011-06-30
0  Barking and Dagenham                        187029
1                Barnet                        357538
2                Bexley                        232774
3                 Brent                        312245
4               Bromley                        310554

In [20]:
# Select name and the latest population 

df_GL1 = df_GL[['Name','PopulationEstimate2011-06-30']]
df_GL1.head()

Name  PopulationEstimate2011-06-30
0  Barking and Dagenham                        187029
1                Barnet                        357538
2                Bexley                        232774
3                 Brent                        312245
4               Bromley                        310554

In [21]:
# Rename the column title Name as Borough and the PopulationEstimate2017-06-30 as Population

df_GL1.rename(columns={'Name':'Borough', 'PopulationEstimate2011-06-30':'Population'}, inplace=True)
df_GL1.head()

/opt/ibm/conda/miniconda3/lib/python3.5/site-packages/pandas/core/frame.py:3027: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)


Borough  Population
0  Barking and Dagenham      187029
1                Barnet      357538
2                Bexley      232774
3                 Brent      312245
4               Bromley      310554

In [22]:
# Compute the total number of Borough in Greater London

No_Borough_GL = len(df_GL1.index)
print('Total Number of Borough in Greater Londond:{}'.format (No_Borough_GL))

Total Number of Borough in Greater Londond:33


In [23]:
# Compute total population in Greater London 

Total_Population_GL = df_GL1['Population'].sum()
print('Total Population of Greater London is:{}'.format (Total_Population_GL))

Total Population of Greater London is:8204407


In [24]:
# Identify the Borough which has max population size in Greater London
 
df_GL1.loc[df_GL1['Population'].idxmax()]

Borough       Croydon
Population     364815
Name: 8, dtype: object

In [25]:
# Identify the Borough which has min population size in Greater London
 
df_GL1.loc[df_GL1['Population'].idxmin()]

Borough       City of London
Population              7412
Name: 6, dtype: object

Greater London has thiry three boroughs (including City of London).  Indeed City of London is not a brough but an independent county, but it this project it counts as brough. London Among all, borough called 'Croydon' has the highest population size of 364,815 wheras the borough named 'City of London' has the least population size which is 7,412.

##  Visualize population of Greater London in each borough

In [26]:
# Greater London latitude and longitude values

latitude =  51.508411 
longitude = -0.125364

In [27]:
# download Greter London geojson file

!wget --quiet   http://darribas.org/gds15/content/labs/data/london_boroughs.geojson -O GL.json
    
print('GeoJSON file downloaded!')   

GeoJSON file downloaded!


In [28]:
# create map and display it

GL_geo = r'GL.json' # geojson file

# create a plain world map
GL_map = folium.Map(location=[latitude, longitude], zoom_start = 9)

# generate choropleth map using the total population of each borough in Greater London
GL_map.choropleth(
    geo_data=GL_geo,
    data=df_GL1,
    columns=['Borough', 'Population'],
    key_on='feature.properties.name',
    fill_color='YlOrRd', 
    fill_opacity=0.7, 
    line_opacity=0.2,
    legend_name='Population Size of Greater London 2010'
)

# display map

GL_map

It can be clearly seen from the choropleth map that there are many broughts in Greater London with population size above 300,000.

## Comparison of population size and number of borough in New York City and Greater London


### A. Number of Borough


In [29]:
print('Number of Borough in New York City is : {}'. format (No_Borough_NYC) ,'Number of Greater London is: {}'.format(No_Borough_GL) )

Number of Borough in New York City is : 5 Number of Greater London is: 33


### B. Size of Population

In [30]:
print('Total Population Size of New York City is: {}'. format (Total_Population_NYC) ,'Total Population Size of Greater London is: {}'.format(Total_Population_GL))

Total Population Size of New York City is: 8175133 Total Population Size of Greater London is: 8204407


New York City has five boroughs whereas Greater London has 33 boroughs. Though both cities have different number of boroughs, their population is almost equal. The population size of New York City is 8,175,133 and Greater London has 8,204,407.

The main objective of this capstone project is to explore and get insight regarding which city is more eco- and vegan-friendly for health and environmental conscious travellers from all over the world. In-depth geolocation exploration of both cities are performed below to identify the best eco- and vegan-friendly city.

# Geolocation exploration and cluster of the neighborhoods in New York City


#### Import necessary libraries

In [31]:
!conda install -c conda-forge geopy --yes 
from geopy.geocoders import Nominatim # module to convert an address into latitude and longitude values
import random # library for random number generation

# libraries for displaying images
from IPython.display import Image 
from IPython.core.display import HTML 
    
# tranforming json file into a pandas dataframe library
from pandas.io.json import json_normalize

print('Libraries imported.')

Solving environment: done

# All requested packages already installed.

Solving environment: done

# All requested packages already installed.

Folium installed
Libraries imported.


In [32]:
# The code was removed by Watson Studio for sharing.

In [33]:
address = 'Manhattan'

geolocator = Nominatim()
location = geolocator.geocode(address)
latitude = location.latitude
longitude = location.longitude
print(latitude, longitude)

/opt/ibm/conda/miniconda3/lib/python3.5/site-packages/geopy/geocoders/osm.py:143: UserWarning: Using Nominatim with the default "geopy/1.17.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  UserWarning


40.7900869 -73.9598295


# 1. Search for a specific venue category in New York City

## 1.1 The venue catagory is vegan restaurant within 2.5 km radius from manhattan center.

In [34]:
search_query = 'vegan'
radius = 2500
print(search_query + ' .... OK!')

vegan .... OK!


#### Define the corresponding URL

In [35]:
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)

In [36]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5bd080c31ed2194288946175'},
 'response': {'venues': [{'categories': [{'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/vegetarian_',
       'suffix': '.png'},
      'id': '4bf58dd8d48988d1d3941735',
      'name': 'Vegetarian / Vegan Restaurant',
      'pluralName': 'Vegetarian / Vegan Restaurants',
      'primary': True,
      'shortName': 'Vegetarian / Vegan'}],
    'hasPerk': False,
    'id': '53172dc7498e5147c4012f34',
    'location': {'address': '55 St. Nicholas',
     'cc': 'US',
     'city': 'New York',
     'country': 'United States',
     'crossStreet': 'West 113th',
     'distance': 1318,
     'formattedAddress': ['55 St. Nicholas (West 113th)',
      'New York, NY 10026',
      'United States'],
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.800625,
       'lng': -73.952693}],
     'lat': 40.800625,
     'lng': -73.952693,
     'postalCode': '10026',
     'state': 'NY'},
    'name': 'Seasoned Vegan',
    'refe

#### Get relevant part of JSON and transform it into a pandas dataframe

In [37]:
# assign relevant part of JSON to venues

venues = results['response']['venues']

# tranform venues into a dataframe

dataframe = json_normalize(venues)
dataframe.head()

categories delivery.id  \
0  [{'id': '4bf58dd8d48988d1d3941735', 'shortName...         NaN   
1  [{'id': '4bf58dd8d48988d139941735', 'shortName...         NaN   
2  [{'id': '4bf58dd8d48988d1d3941735', 'shortName...      348241   

                delivery.provider.icon.name  \
0                                       NaN   
1                                       NaN   
2  /delivery_provider_seamless_20180129.png   

           delivery.provider.icon.prefix delivery.provider.icon.sizes  \
0                                    NaN                          NaN   
1                                    NaN                          NaN   
2  https://igx.4sqi.net/img/general/cap/                     [40, 50]   

  delivery.provider.name                                       delivery.url  \
0                    NaN                                                NaN   
1                    NaN                                                NaN   
2               seamless  https://www.seamless.com/menu/ginger-root-1164...   

   hasPerk                        id location.address      ...       \
0    False  53172dc7498e5147c4012f34  55 St. Nicholas      ...        
1    False  4dd990c22271c5d36d6fa93d    417 E 90th St      ...        
2    False  586779ec07ac0762ed926424     1164 1st Ave      ...        

  location.crossStreet location.distance  \
0           West 113th              1318   
1           1st & York              1606   
2                  NaN              3073   

                           location.formattedAddress  \
0  [55 St. Nicholas (West 113th), New York, NY 10...   
1  [417 E 90th St (1st & York), New York, NY 1012...   
2  [1164 1st Ave, New York, NY 10065, United States]   

                             location.labeledLatLngs  location.lat  \
0  [{'lng': -73.952693, 'label': 'display', 'lat'...     40.800625   
1  [{'lng': -73.94696356666667, 'label': 'display...     40.779435   
2  [{'lng': -73.9595827460289, 'label': 'display'...     40.762475   

  location.lng location.postalCode  location.state  \
0   -73.952693               10026              NY   
1   -73.946964               10128              NY   
2   -73.959583               10065              NY   

                           name    referralId  
0                Seasoned Vegan  v-1540391107  
1              The Vegan Palace  v-1540391107  
2  Ginger Root Vegan Restaurant  v-1540391107  

[3 rows x 23 columns]

#### Define information of interest and filter dataframe

In [38]:
# keep only columns that include venue name, and anything that is associated with location

filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue

def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row

dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term

dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

name                     categories  \
0                Seasoned Vegan  Vegetarian / Vegan Restaurant   
1              The Vegan Palace                      Synagogue   
2  Ginger Root Vegan Restaurant  Vegetarian / Vegan Restaurant   

           address  cc      city        country crossStreet  distance  \
0  55 St. Nicholas  US  New York  United States  West 113th      1318   
1    417 E 90th St  US  New York  United States  1st & York      1606   
2     1164 1st Ave  US  New York  United States         NaN      3073   

                                    formattedAddress  \
0  [55 St. Nicholas (West 113th), New York, NY 10...   
1  [417 E 90th St (1st & York), New York, NY 1012...   
2  [1164 1st Ave, New York, NY 10065, United States]   

                                      labeledLatLngs        lat        lng  \
0  [{'lng': -73.952693, 'label': 'display', 'lat'...  40.800625 -73.952693   
1  [{'lng': -73.94696356666667, 'label': 'display...  40.779435 -73.946964   
2  [{'lng': -73.9595827460289, 'label': 'display'...  40.762475 -73.959583   

  postalCode state                        id  
0      10026    NY  53172dc7498e5147c4012f34  
1      10128    NY  4dd990c22271c5d36d6fa93d  
2      10065    NY  586779ec07ac0762ed926424

#### The dataframe encompass synagogue among the lists of vegan restaurants as its name is 'The Vegan Palace'. So it has to be removed from the list of vegan restaurants

In [39]:
# Flitter the dataframe to obtain only categories of Vegetarian / Vegan Restaurant

dataframe_filtered = dataframe_filtered.loc[dataframe_filtered['categories'] == 'Vegetarian / Vegan Restaurant'].reset_index()
dataframe_filtered

index                          name                     categories  \
0      0                Seasoned Vegan  Vegetarian / Vegan Restaurant   
1      2  Ginger Root Vegan Restaurant  Vegetarian / Vegan Restaurant   

           address  cc      city        country crossStreet  distance  \
0  55 St. Nicholas  US  New York  United States  West 113th      1318   
1     1164 1st Ave  US  New York  United States         NaN      3073   

                                    formattedAddress  \
0  [55 St. Nicholas (West 113th), New York, NY 10...   
1  [1164 1st Ave, New York, NY 10065, United States]   

                                      labeledLatLngs        lat        lng  \
0  [{'lng': -73.952693, 'label': 'display', 'lat'...  40.800625 -73.952693   
1  [{'lng': -73.9595827460289, 'label': 'display'...  40.762475 -73.959583   

  postalCode state                        id  
0      10026    NY  53172dc7498e5147c4012f34  
1      10065    NY  586779ec07ac0762ed926424

#### Let's visualize vegan restaurants which are avilable within 2.5 km from Manhattan center. 

In [40]:
# generate map centred around the Manhattan center.

venues_map = folium.Map(location=[latitude, longitude], zoom_start=13) 

# add a red circle marker to represent center of Manhattan

folium.features.CircleMarker(
    [latitude, longitude],
    radius=10,
    color='red',
    popup='Manhattan Vegan Restaurants',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add the vegan restaurants as blue circle markers

for lat, lng, label in zip(dataframe_filtered.lat, dataframe_filtered.lng, dataframe_filtered.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map


## 1.2 The venue catagory is metro station within 2.5 km radius from manhattan center.


In [41]:
search_query = 'metro station'
radius = 2500
print(search_query + ' .... OK!')

metro station .... OK!


In [42]:
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)

In [43]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5bd080c36a6071462a203482'},
 'response': {'venues': [{'categories': [{'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/travel/trainstation_',
       'suffix': '.png'},
      'id': '4bf58dd8d48988d129951735',
      'name': 'Train Station',
      'pluralName': 'Train Stations',
      'primary': True,
      'shortName': 'Train Station'}],
    'hasPerk': False,
    'id': '49de0156f964a52021601fe3',
    'location': {'address': '101 E 125th St',
     'cc': 'US',
     'city': 'New York',
     'country': 'United States',
     'crossStreet': 'at Park Ave',
     'distance': 2470,
     'formattedAddress': ['101 E 125th St (at Park Ave)',
      'New York, NY 10035',
      'United States'],
     'lat': 40.805484558414754,
     'lng': -73.93872320496561,
     'postalCode': '10035',
     'state': 'NY'},
    'name': 'Metro North - Harlem - 125th Street Station',
    'referralId': 'v-1540391107'},
   {'categories': [{'icon': {'prefix': 'https://ss3.4sqi.ne

#### Get relevant part of JSON and transform it into a pandas dataframe

In [44]:
# assign relevant part of JSON to venues

venues = results['response']['venues']

# tranform venues into a dataframe

dataframe = json_normalize(venues)
dataframe.head()

categories delivery.id  \
0  [{'id': '4bf58dd8d48988d129951735', 'shortName...         NaN   
1  [{'id': '4bf58dd8d48988d147941735', 'shortName...        2191   
2  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...         NaN   
3  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...         NaN   
4  [{'id': '4bf58dd8d48988d172941735', 'shortName...         NaN   

                delivery.provider.icon.name  \
0                                       NaN   
1  /delivery_provider_seamless_20180129.png   
2                                       NaN   
3                                       NaN   
4                                       NaN   

           delivery.provider.icon.prefix delivery.provider.icon.sizes  \
0                                    NaN                          NaN   
1  https://igx.4sqi.net/img/general/cap/                     [40, 50]   
2                                    NaN                          NaN   
3                                    NaN                          NaN   
4                                    NaN                          NaN   

  delivery.provider.name                                       delivery.url  \
0                    NaN                                                NaN   
1               seamless  https://www.seamless.com/menu/metro-diner-2641...   
2                    NaN                                                NaN   
3                    NaN                                                NaN   
4                    NaN                                                NaN   

   hasPerk                        id location.address     ...       \
0    False  49de0156f964a52021601fe3   101 E 125th St     ...        
1    False  4ccc8124c0378cfa0f2a8748    2641 Broadway     ...        
2    False  4adf9445f964a520c47b21e3        W 72nd St     ...        
3    False  51c23f84498e9f5f2d447f77        Manhattan     ...        
4    False  4b2cffbff964a52015cc24e3    229 E 85th St     ...        

                           location.formattedAddress  \
0  [101 E 125th St (at Park Ave), New York, NY 10...   
1  [2641 Broadway (100th St), New York, NY 10025,...   
2  [W 72nd St (at Broadway), New York, NY 10023, ...   
3           [Manhattan, New York, NY, United States]   
4  [229 E 85th St (at 2nd Ave.), New York, NY 100...   

                             location.labeledLatLngs location.lat  \
0                                                NaN    40.805485   
1  [{'lng': -73.97018820978309, 'label': 'display...    40.797366   
2                                                NaN    40.778873   
3  [{'lng': -73.9597222, 'label': 'display', 'lat...    40.790278   
4  [{'lng': -73.95267031984743, 'label': 'display...    40.777435   

  location.lng  location.neighborhood location.postalCode location.state  \
0   -73.938723                    NaN               10035             NY   
1   -73.970188                    NaN               10025             NY   
2   -73.981938                    NaN               10023             NY   
3   -73.959722                    NaN                 NaN             NY   
4   -73.952670                    NaN               10028             NY   

                                          name    referralId venuePage.id  
0  Metro North - Harlem - 125th Street Station  v-1540391107          NaN  
1                                  Metro Diner  v-1540391107          NaN  
2                 MTA Subway - 72nd St (1/2/3)  v-1540391107          NaN  
3                            Manhattan Station  v-1540391107          NaN  
4              US Post Office - Gracie Station  v-1540391107          NaN  

[5 rows x 25 columns]

#### Define information of interest and filter dataframe

In [45]:
# keep only columns that include venue name, and anything that is associated with location

filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue

def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row

dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term

dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

name  \
0         Metro North - Harlem - 125th Street Station   
1                                         Metro Diner   
2                        MTA Subway - 72nd St (1/2/3)   
3                                   Manhattan Station   
4                     US Post Office - Gracie Station   
5            MTA Subway - Cathedral Pkwy/110th St (1)   
6                  US Post Office - Cathedral Station   
7                               Metro North - Track 1   
8                US Post Office - Planetarium Station   
9                  US Post Office - Yorkville Station   
10               US Post Office - Morningside Station   
11  The Metropolitan Museum of Art (Metropolitan M...   
12                          Metropolitan Museum Steps   
13                              Metro North - Track 3   
14                                  Metro by T-Mobile   
15                                  Metro by T-Mobile   
16               USPS Post Office - Hell Gate Station   
17                                        Metro Drugs   
18                                    Metro Frame Art   
19                   US Post Office - Ansonia Station   
20                   Metro Bicycles - Upper East Side   
21                                  Citi Bike Station   
22                                  Metro by T-Mobile   
23                       MTA Subway - 96th St (1/2/3)   
24                       MTA Subway - 86th St (4/5/6)   
25                              Metro North - Track 2   
26                         MTA Subway - 96th St (B/C)   
27  Metro Physical Therapy & Sport Rehabilitation,...   
28                        MTA Subway - 103rd St (B/C)   
29  MTA Capital Construction - 96th Street Station...   
30                         AmNY/Metro Newspaper Stand   
31                              Metro Local Locksmith   
32                                          Metro PCS   
33                          NYCHA - Metro North Plaza   
34                                  Metro Contractors   
35                          MTA Subway - 103rd St (6)   
36     MTA Subway - 110th St/Central Park North (2/3)   
37                                  Metro by T-Mobile   
38                          MTA Subway - 103rd St (1)   
39                           MTA Subway - 96th St (6)   
40                                      Metro Genesis   
41  MTA Subway - 81st St/Museum of Natural History...   
42                                         Metro Bike   
43                              Metro II Beauty Salon   
44                                        Metro North   
45                US Post Office - Lenox Hill Station   
46                                     Metro Bicycles   
47                                   Citibike station   
48                                  Metro by T-Mobile   
49                                  Metro by T-Mobile   

                    categories                        address  cc      city  \
0                Train Station                 101 E 125th St  US  New York   
1                        Diner                  2641 Broadway  US  New York   
2                Metro Station                      W 72nd St  US  New York   
3                Metro Station                      Manhattan  US  New York   
4                  Post Office                  229 E 85th St  US  New York   
5                Metro Station                 Cathedral Pkwy  US  New York   
6                  Post Office                 215 W 104th St  US  New York   
7                     Platform      Harlem - 125th St Station  US  New York   
8                  Post Office                  127 W 83rd St  US  New York   
9                  Post Office                   1617 3rd Ave  US  New York   
10                 Post Office                 232 W 116th St  US  New York   
11                  Art Museum                   1000 5th Ave  US  New York   
12                       Plaza                   1000 5th Ave  US  New York   
13               Train Station     

#### It can be observed that the dataframe entails unrelated categories such as Metro Diner, US Post Office - Gracie Station and Metro by T-Mobile. Thus the dataframe shall be flittered to comprise only categories of metro stations

In [46]:
# Flitter the dataframe to obtain only categories of metro stations

dataframe_filtered = dataframe_filtered.loc[dataframe_filtered['categories'].isin(['Metro Station','Train Station']) ].reset_index()
dataframe_filtered

index                                               name     categories  \
0       0        Metro North - Harlem - 125th Street Station  Train Station   
1       2                       MTA Subway - 72nd St (1/2/3)  Metro Station   
2       3                                  Manhattan Station  Metro Station   
3       5           MTA Subway - Cathedral Pkwy/110th St (1)  Metro Station   
4      13                              Metro North - Track 3  Train Station   
5      23                       MTA Subway - 96th St (1/2/3)  Metro Station   
6      24                       MTA Subway - 86th St (4/5/6)  Metro Station   
7      26                         MTA Subway - 96th St (B/C)  Metro Station   
8      28                        MTA Subway - 103rd St (B/C)  Metro Station   
9      35                          MTA Subway - 103rd St (6)  Metro Station   
10     36     MTA Subway - 110th St/Central Park North (2/3)  Metro Station   
11     38                          MTA Subway - 103rd St (1)  Metro Station   
12     39                           MTA Subway - 96th St (6)  Metro Station   
13     41  MTA Subway - 81st St/Museum of Natural History...  Metro Station   

                      address  cc      city        country  \
0              101 E 125th St  US  New York  United States   
1                   W 72nd St  US  New York  United States   
2                   Manhattan  US  New York  United States   
3              Cathedral Pkwy  US  New York  United States   
4   Harlem - 125th St Station  US  New York  United States   
5                    Broadway  US  New York  United States   
6          1276 Lexington Ave  US  New York  United States   
7                     96th St  US  New York  United States   
8                  W 103rd St  US  New York  United States   
9                    103rd St  US  New York  United States   
10  110th St & Malcolm X Blvd  US  New York  United States   
11                W 103rd St.  US  New York  United States   
12                    96th St  US  New York  United States   
13               West 81st St  US  New York  United States   

                 crossStreet  distance  \
0                at Park Ave      2470   
1                at Broadway      2242   
2                        NaN        23   
3                at Broadway      1689   
4   at E 125th St & Park Ave      2432   
5     btwn W 96 St & W 94 St      1131   
6                  E 86th St      1233   
7       at Central Park West       458   
8          Central Park West       704   
9              Lexington Ave      1027   
10        at St Nicholas Ave      1146   
11               at Broadway      1255   
12          at Lexington Ave       880   
13         Central Park West      1359   

                                     formattedAddress  \
0   [101 E 125th St (at Park Ave), New York, NY 10...   
1   [W 72nd St (at Broadway), New York, NY 10023, ...   
2            [Manhattan, New York, NY, United States]   
3   [Cathedral Pkwy (at Broadway), New York, NY 10...   
4   [Harlem - 125th St Station (at E 125th St & Pa...   
5   [Broadway (btwn W 96 St & W 94 St), New York, ...   
6   [1276 Lexington Ave (E 86th St), New York, NY ...   
7   [96th St (at Central Park West), New York, NY ...   
8   [W 103rd St (Central Park West), New York, NY ...   
9   [103rd St (Lexington Ave), New York, NY 10029,...   
10  [110th St & Malcolm X Blvd (at St Nicholas Ave...   
11  [W 103rd St. (at Broadway), New York, NY 10029...   
12  [96th St (at Lexington Ave), New York, NY 1012...   
13  [West 81st St (Central Park West), New York, N...   

                                       labeledLatLngs        lat        lng  \
0                                                 NaN  40.805485 -73.938723   
1                                                 NaN  40.778873 -73.981938   
2   [{'lng': -73.9597222, 'label': 'display', 'lat...  40.790278 -73.959722   
3   [{'lng': -73.96670381564047, 'label': 'display...  40.804344 -73.966704   
4   [

#### Let's visualize metro stations which are avilable within 2.5 km from Manhattan center. 

In [47]:
# generate map centred around the Manhattan center.

venues_map = folium.Map(location=[latitude, longitude], zoom_start=13) 

# add a red circle marker to represent center of manhattan

folium.features.CircleMarker(
    [latitude, longitude],
    radius=10,
    color='red',
    popup='Manhattan Metro Stations',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add metro stations as blue circle markers

for lat, lng, label in zip(dataframe_filtered.lat, dataframe_filtered.lng, dataframe_filtered.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map


## 1.3 The venue catagory is bike rental service within 2.5 km radius from manhattan center.


In [48]:
search_query = 'bike rental'
radius = 2500
print(search_query + ' .... OK!')

bike rental .... OK!


In [49]:
url = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude, longitude, VERSION, search_query, radius, LIMIT)

In [50]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5bd080c59fb6b752c89c16dd'},
 'response': {'venues': [{'categories': [],
    'hasPerk': False,
    'id': '4da2311c9935a0939683b06f',
    'location': {'address': 'Cock Sucker',
     'cc': 'US',
     'city': 'Cliffside',
     'country': 'United States',
     'distance': 2985,
     'formattedAddress': ['Cock Sucker', 'Cliffside, NY', 'United States'],
     'labeledLatLngs': [{'label': 'display',
       'lat': 40.816167,
       'lng': -73.968066}],
     'lat': 40.816167,
     'lng': -73.968066,
     'state': 'NY'},
    'name': 'Medium Daves Bike Rental Service!',
    'referralId': 'v-1540391109'},
   {'categories': [{'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/shops/airport_rentalcar_',
       'suffix': '.png'},
      'id': '4bf58dd8d48988d1ef941735',
      'name': 'Rental Car Location',
      'pluralName': 'Rental Car Locations',
      'primary': True,
      'shortName': 'Rental Car'}],
    'hasPerk': False,
    'id': '4fe888237beb3371b92

#### Get relevant part of JSON and transform it into a pandas dataframe

In [51]:
# assign relevant part of JSON to venues

venues = results['response']['venues']

# tranform venues into a dataframe

dataframe = json_normalize(venues)
dataframe.head()

categories  hasPerk  \
0                                                 []    False   
1  [{'id': '4bf58dd8d48988d1ef941735', 'shortName...    False   
2  [{'id': '4bf58dd8d48988d1ef941735', 'shortName...    False   
3  [{'id': '4e4c9077bd41f78e849722f9', 'shortName...    False   
4  [{'id': '4bf58dd8d48988d159941735', 'shortName...    False   

                         id                        location.address  \
0  4da2311c9935a0939683b06f                             Cock Sucker   
1  4fe888237beb3371b9232a98  420 East 90th Street, Uptown East 90th   
2  4fe888767beb3371b9233a4c     216 West 76th Street, (at Broadway)   
3  59209fd3c62b4920e267a736                          Central Park N   
4  4e65dc171fc747ca49d7d2d3             168th Street to 86th Street   

  location.cc location.city location.country  \
0          US     Cliffside    United States   
1          US      New York    United States   
2          US      New York    United States   
3          US      New York    United States   
4          US      New York    United States   

               location.crossStreet  location.distance  \
0                               NaN               2985   
1             btwn 1st and York Ave               1718   
2     btwn Broadway & Amsterdam Ave               1987   
3        at Adam C. Powell Jr. Blvd               1101   
4  8th Avenue & St. Nicholas Avenue               1172   

                           location.formattedAddress  \
0        [Cock Sucker, Cliffside, NY, United States]   
1  [420 East 90th Street, Uptown East 90th (btwn ...   
2  [216 West 76th Street, (at Broadway) (btwn Bro...   
3  [Central Park N (at Adam C. Powell Jr. Blvd), ...   
4  [168th Street to 86th Street (8th Avenue & St....   

                             location.labeledLatLngs  location.lat  \
0  [{'lng': -73.968066, 'label': 'display', 'lat'...     40.816167   
1  [{'lng': -73.946064, 'label': 'display', 'lat'...     40.778704   
2  [{'lng': -73.980388, 'label': 'display', 'lat'...     40.781349   
3  [{'lng': -73.955681, 'label': 'display', 'lat'...     40.799470   
4  [{'lng': -73.95808339118958, 'label': 'display...     40.800540   

   location.lng location.neighborhood location.postalCode location.state  \
0    -73.968066                   NaN                 NaN             NY   
1    -73.946064                   NaN               10028             NY   
2    -73.980388                   NaN               10023             NY   
3    -73.955681                   NaN               10025             NY   
4    -73.958083                   NaN                 NaN             NY   

                                                name    referralId  \
0                  Medium Daves Bike Rental Service!  v-1540391109   
1                                    Avis Car Rental  v-1540391109   
2                                    Avis Car Rental  v-1540391109   
3                                  Citi Bike Station  v-1540391109   
4  St. Nicholas & 8th Avenue Bike Path & Greenway...  v-1540391109   

  venuePage.id  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

#### Define information of interest and filter dataframe

In [52]:
# keep only columns that include venue name, and anything that is associated with location

filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue

def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row

dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term

dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

name  \
0                   Medium Daves Bike Rental Service!   
1                                     Avis Car Rental   
2                                     Avis Car Rental   
3                                   Citi Bike Station   
4   St. Nicholas & 8th Avenue Bike Path & Greenway...   
5                                   Citi Bike Station   
6                                   Budget Car Rental   
7                                   Citi Bike Station   
8                                        Rental Deals   
9                                   AAMCAR Car Rental   
10   7th Ave (Adam Clayton Powell Jr. Blvd) Bike Lane   
11                                  Citi Bike Station   
12                                     The Bike Caves   
13                                 Thrifty Car Rental   
14                                  Citi Bike Station   
15             St Nicholas Ave Bike Lane, NYC Cycling   
16                                  Central Park Loop   
17                                    Avis Car Rental   
18                                  Citi Bike Station   
19                                  Citi Bike Station   
20                                      Bike New York   
21                                National Car Rental   
22                                  Citi Bike Station   
23                     Bettina Equities Rental Office   
24                                  Citi Bike Station   
25                                            Bike Ss   
26                               Innovation Bike Shop   
27                                  Citi Bike Station   
28                                  Citi Bike Station   
29                                  citi bike station   
30                                  Citi Bike Station   
31                Citi Bike Station - 67th & Broadway   
32                                    Avis Car Rental   
33                              90th Street Bike Lane   
34   Bike And Roll Central Park (Tavern On The Green)   
35                                  Citi Bike Station   
36                                  Citi Bike Station   
37                              Citi Bike 81st & Park   
38                                  citi bike station   
39                                  Citi Bike Station   
40                                  Citi Bike Station   
41                      Citi Bike Station 63rd /b-way   
42                              Moroccan Props Rental   
43                 Comfort Express Bus Charter Rental   
44                    Hudson River Greenway Bike Path   
45                                 Champion Bike Shop   
46                                  Citi Bike Station   
47                      Citi Bike 103rd and Lexington   
48                              Heavy Metal Bike Shop   
49                 Citi Bike Station 91st and 2nd ave   

                  categories                                 address  cc  \
0                       None                             Cock Sucker  US   
1        Rental Car Location  420 East 90th Street, Uptown East 90th  US   
2        Rental Car Location     216 West 76th Street, (at Broadway)  US   
3   Bike Rental / Bike Share                          Central Park N  US   
4                      Trail             168th Street to 86th Street  US   
5   Bike Rental / Bike Share                                110th St  US   
6        Rental Car Location          300 E 87th St, (2nd Ave &87th)  US   
7   Bike Rental / Bike Share                                     NaN  US   
8         Miscellaneous Shop                 730 Columbus Ave Apt 8B  US   
9        Rental Car Location                           315 W 96th St  US   
10                Bike Trail                              W 110th St  US   
11  Bike Rental / Bike Share                 W. 95th & Columbus Ave.  US   
12                 Bike Shop                       Under 96th Street  US   
13       Rental Car Location                           148 W 83rd St  US   
1

#### It can be clealry seen that the dataframe entails unrelated categories such as Avis Car Rental, Bike Path and Miscellaneous Shop. Hence, the dataframe shall be flittered to comprise only categories of Bike Rental / Bike Share

In [53]:
# Flitter the dataframe to obtain only categories of bike rental

dataframe_filtered = dataframe_filtered.loc[dataframe_filtered['categories'] == 'Bike Rental / Bike Share'].reset_index()
dataframe_filtered

index                                 name                categories  \
0       3                    Citi Bike Station  Bike Rental / Bike Share   
1       5                    Citi Bike Station  Bike Rental / Bike Share   
2       7                    Citi Bike Station  Bike Rental / Bike Share   
3      11                    Citi Bike Station  Bike Rental / Bike Share   
4      14                    Citi Bike Station  Bike Rental / Bike Share   
5      18                    Citi Bike Station  Bike Rental / Bike Share   
6      19                    Citi Bike Station  Bike Rental / Bike Share   
7      22                    Citi Bike Station  Bike Rental / Bike Share   
8      24                    Citi Bike Station  Bike Rental / Bike Share   
9      25                              Bike Ss  Bike Rental / Bike Share   
10     27                    Citi Bike Station  Bike Rental / Bike Share   
11     28                    Citi Bike Station  Bike Rental / Bike Share   
12     29                    citi bike station  Bike Rental / Bike Share   
13     30                    Citi Bike Station  Bike Rental / Bike Share   
14     31  Citi Bike Station - 67th & Broadway  Bike Rental / Bike Share   
15     35                    Citi Bike Station  Bike Rental / Bike Share   
16     36                    Citi Bike Station  Bike Rental / Bike Share   
17     37                Citi Bike 81st & Park  Bike Rental / Bike Share   
18     38                    citi bike station  Bike Rental / Bike Share   
19     39                    Citi Bike Station  Bike Rental / Bike Share   
20     40                    Citi Bike Station  Bike Rental / Bike Share   
21     41        Citi Bike Station 63rd /b-way  Bike Rental / Bike Share   
22     46                    Citi Bike Station  Bike Rental / Bike Share   
23     47        Citi Bike 103rd and Lexington  Bike Rental / Bike Share   
24     49   Citi Bike Station 91st and 2nd ave  Bike Rental / Bike Share   

                               address  cc      city        country  \
0                       Central Park N  US  New York  United States   
1                             110th St  US  New York  United States   
2                                  NaN  US  New York  United States   
3              W. 95th & Columbus Ave.  US  New York  United States   
4                                  NaN  US  New York  United States   
5                    Central Park West  US  New York  United States   
6                         Third Avenue  US  New York  United States   
7                                  NaN  US  New York  United States   
8              E 97th St & Madison Ave  US  New York  United States   
9                                  NaN  US  New York  United States   
10  Central Park West & W 106th Street  US  New York  United States   
11                 5th Ave & E 88th St  US  New York  United States   
12                                 NaN  US  New York  United States   
13                      E 110th Street  US  New York  United States   
14                                 NaN  US  New York  United States   
15                 2nd Ave & E 96th St  US  New York  United States   
16                                 NaN  US  New York  United States   
17                           E 81St st  US  New York  United States   
18                                 NaN  US  New York  United States   
19                             1st Ave  US  New York  United States   
20                                 NaN  US  New York  United States   
21                                 NaN  US  New York  United States   
22      St Nicholas Av & Manhattan Ave  US  New York  United States   
23                                 NaN  US  New York  United States   
24                                 NaN  US  New York  United States   

                   crossStreet  distance  \
0   at Adam C. Powell Jr. Blvd      1101   
1                     Broadway      1686   
2                          NaN      1288   
3   

#### Let's visualize bike rental services which are avilable within 2.5 km from Manhattan center. 

In [54]:
# generate map centred around the City of London center.

venues_map = folium.Map(location=[latitude, longitude], zoom_start=13) 

# add a red circle marker to represent center of Manhattan

folium.features.CircleMarker(
    [latitude, longitude],
    radius=10,
    color='red',
    popup='Manhattan Bike Rental',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add bike rental services as blue circle markers

for lat, lng, label in zip(dataframe_filtered.lat, dataframe_filtered.lng, dataframe_filtered.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map


# 2. Search for a specific venue category in Greater London

## 2.1 The venue catagory is vegan restaurant within 2.5 km radius from City of London.

In [55]:
# The code was removed by Watson Studio for sharing.

In [56]:
address1 = 'City of London'

geolocator1 = Nominatim()
location1 = geolocator1.geocode(address1)
latitude1 = location1.latitude
longitude1 = location1.longitude
print(latitude1, longitude1)

/opt/ibm/conda/miniconda3/lib/python3.5/site-packages/geopy/geocoders/osm.py:143: UserWarning: Using Nominatim with the default "geopy/1.17.0" `user_agent` is strongly discouraged, as it violates Nominatim's ToS https://operations.osmfoundation.org/policies/nominatim/ and may possibly cause 403 and 429 HTTP errors. Please specify a custom `user_agent` with `Nominatim(user_agent="my-application")` or by overriding the default `user_agent`: `geopy.geocoders.options.default_user_agent = "my-application"`. In geopy 2.0 this will become an exception.
  UserWarning


51.5156177 -0.0919983


In [57]:
search_query1 = 'vegan restaurant'
radius1 = 2500
print(search_query + ' .... OK!')

bike rental .... OK!


In [58]:
url1 = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude1, longitude1, VERSION, search_query1, radius1, LIMIT)

In [59]:
results = requests.get(url1).json()
results

{'meta': {'code': 200, 'requestId': '5bd080c7f594df1dccc928df'},
 'response': {'venues': [{'categories': [{'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/vegetarian_',
       'suffix': '.png'},
      'id': '4bf58dd8d48988d1d3941735',
      'name': 'Vegetarian / Vegan Restaurant',
      'pluralName': 'Vegetarian / Vegan Restaurants',
      'primary': True,
      'shortName': 'Vegetarian / Vegan'}],
    'hasPerk': False,
    'id': '5848791af68d8d38cfcf6446',
    'location': {'address': '104 Brick Ln',
     'cc': 'GB',
     'city': 'London',
     'country': 'United Kingdom',
     'distance': 1473,
     'formattedAddress': ['104 Brick Ln',
      'London',
      'Greater London',
      'E1 6RL',
      'United Kingdom'],
     'labeledLatLngs': [{'label': 'display',
       'lat': 51.51973095696915,
       'lng': -0.07178295871370416}],
     'lat': 51.51973095696915,
     'lng': -0.07178295871370416,
     'postalCode': 'E1 6RL',
     'state': 'Greater London'},
    'name': 'Ve

#### Get relevant part of JSON and transform it into a pandas dataframe

In [60]:
# assign relevant part of JSON to venues

venues = results['response']['venues']

# tranform venues into a dataframe

dataframe = json_normalize(venues)
dataframe

categories  hasPerk  \
0   [{'id': '4bf58dd8d48988d1d3941735', 'shortName...    False   
1   [{'id': '4f04af1f2fb6e1c99f3db0bb', 'shortName...    False   
2   [{'id': '4bf58dd8d48988d1cc941735', 'shortName...    False   
3   [{'id': '52e81612bcbc57f1066b7a05', 'shortName...    False   
4   [{'id': '4bf58dd8d48988d1d3941735', 'shortName...    False   
5   [{'id': '4bf58dd8d48988d1c4941735', 'shortName...    False   
6   [{'id': '4bf58dd8d48988d1c4941735', 'shortName...    False   
7   [{'id': '4bf58dd8d48988d11b941735', 'shortName...    False   
8   [{'id': '4bf58dd8d48988d1cb941735', 'shortName...    False   
9   [{'id': '4bf58dd8d48988d145941735', 'shortName...    False   
10  [{'id': '52f2ab2ebcbc57f1066b8b3d', 'shortName...    False   
11  [{'id': '4f04af1f2fb6e1c99f3db0bb', 'shortName...    False   
12  [{'id': '4bf58dd8d48988d1c4941735', 'shortName...    False   
13  [{'id': '4bf58dd8d48988d149941735', 'shortName...    False   
14  [{'id': '52e81612bcbc57f1066b7a05', 'shortName...    False   
15  [{'id': '4bf58dd8d48988d1d3941735', 'shortName...    False   
16  [{'id': '4bf58dd8d48988d1c4941735', 'shortName...    False   
17  [{'id': '4f04af1f2fb6e1c99f3db0bb', 'shortName...    False   
18  [{'id': '4bf58dd8d48988d1d3941735', 'shortName...    False   
19  [{'id': '4bf58dd8d48988d1d3941735', 'shortName...    False   
20  [{'id': '4bf58dd8d48988d10c941735', 'shortName...    False   
21  [{'id': '4bf58dd8d48988d18f941735', 'shortName...    False   
22  [{'id': '52e81612bcbc57f1066b7a05', 'shortName...    False   
23  [{'id': '4bf58dd8d48988d1d3941735', 'shortName...    False   
24  [{'id': '4bf58dd8d48988d111941735', 'shortName...    False   
25  [{'id': '4bf58dd8d48988d10f941735', 'shortName...    False   
26  [{'id': '4bf58dd8d48988d190941735', 'shortName...    False   
27  [{'id': '4f04af1f2fb6e1c99f3db0bb', 'shortName...    False   
28  [{'id': '52e81612bcbc57f1066b7a05', 'shortName...    False   
29  [{'id': '4bf58dd8d48988d116941735', 'shortName...    False   
30  [{'id': '54f4ba06498e2cf5561da814', 'shortName...    False   
31  [{'id': '4bf58dd8d48988d1d3941735', 'shortName...    False   
32  [{'id': '4bf58dd8d48988d1ce941735', 'shortName...    False   
33  [{'id': '4f04af1f2fb6e1c99f3db0bb', 'shortName...    False   
34  [{'id': '4bf58dd8d48988d145941735', 'shortName...    False   
35  [{'id': '56aa371be4b08b9a8d57350b', 'shortName...    False   
36  [{'id': '4edd64a0c7ddd24ca188df1a', 'shortName...    False   
37  [{'id': '4bf58dd8d48988d1c4941735', 'shortName...    False   
38  [{'id': '4bf58dd8d48988d16d941735', 'shortName...    False   
39  [{'id': '4bf58dd8d48988d16a941735', 'shortName...    False   
40  [{'id': '4bf58dd8d48988d1c4941735', 'shortName...    False   
41  [{'id': '4bf58dd8d48988d149941735', 'shortName...    False   
42  [{'id': '4bf58dd8d48988d10f941735', 'shortName...    False   
43  [{'id': '4f04af1f2fb6e1c99f3db0bb', 'shortName...    False   
44  [{'id': '4bf58dd8d48988d10f941735', 'shortName...    False   
45  [{'id': '4bf58dd8d48988d115941735', 'shortName...    False   
46  [{'id': '4bf58dd8d48988d16d941735', 'shortName...    False   
47  [{'id': '4bf58dd8d48988d16d941735', 'shortName...    False   
48  [{'id': '4bf58dd8d48988d10c941735', 'shortName...    False   
49  [{'id': '4bf58dd8d48988d10f941735', 'shortName...    False   

                          id                  location.address location.cc  \
0   5848791af68d8d38cfcf6446                      104 Brick Ln          GB   
1   4b8fe00ef964a520d86633e3                     34 Foster Ln.          GB   
2   4c5190663940be9a0f2c0f09                      11 Old Jewry          GB   
3   4ad5c5cef964a5206f0321e3                    26 St. John St          GB   
4   59ada1f8febf314589c6f8d5                       64 Brick Ln          GB   
5   4dcc80213151d6d342eb5492                    One New Change          GB   
6   517135e3498eb43c26c78d9e                               NaN          GB   
7   4c1905d2f551ef3bd11d4768                        

#### Define information of interest and filter dataframe

In [61]:
# keep only columns that include venue name, and anything that is associated with location

filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue

def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row

dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term

dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

name                     categories  \
0                   Vegan Burgers by Mooshies  Vegetarian / Vegan Restaurant   
1                       Haz Restaurant & Cafe             Turkish Restaurant   
2              Goodman Steak House Restaurant                     Steakhouse   
3                 St. John Bar and Restaurant             English Restaurant   
4                                   Vegan Yes  Vegetarian / Vegan Restaurant   
5                          Madison Restaurant                     Restaurant   
6                         the gild restaurant                     Restaurant   
7                Wood Street Bar & Restaurant                            Pub   
8                           Vegan Sweet Tooth                     Food Truck   
9                             Kiri Restaurant             Chinese Restaurant   
10  The Little Vegan Pop Up Shop by Superdrug                    Pop-Up Shop   
11                             Haz Restaurant             Turkish Restaurant   
12                   Restaurant - Tate Modern                     Restaurant   
13                    Suchard Thai Restaurant                Thai Restaurant   
14                            TĪNG Restaurant             English Restaurant   
15                            Essential Vegan  Vegetarian / Vegan Restaurant   
16            Off The Wall Bar and Restaurant                     Restaurant   
17         The Best Mangal - Restaurant & Bar             Turkish Restaurant   
18                    Vegan No Blood No Bones  Vegetarian / Vegan Restaurant   
19                     Vegan Veggie Love Cafe  Vegetarian / Vegan Restaurant   
20                  Bleeding Heart Restaurant              French Restaurant   
21                                Tate Modern                     Art Museum   
22                          Bill's Restaurant             English Restaurant   
23                        Vegan Nights London  Vegetarian / Vegan Restaurant   
24                      Nobu Restaurant & Bar            Japanese Restaurant   
25                           Halal Restaurant              Indian Restaurant   
26                             British Museum                 History Museum   
27                             Tas Restaurant             Turkish Restaurant   
28                         The Ivy Restaurant             English Restaurant   
29                 The Cut Bar and Restaurant                            Bar   
30                          Catlin Restaurant            Corporate Cafeteria   
31                         Jakes Vegan Steaks  Vegetarian / Vegan Restaurant   
32      Angler Rooftop Restaurant and Terrace             Seafood Restaurant   
33                             Haz Restaurant             Turkish Restaurant   
34                     Lin's Restaurant & Bar             Chinese Restaurant   
35                                Astro Vegan                     Food Stand   
36                  Kennedy's Fish Restaurant              Fish & Chips Shop   
37                     Great Court Restaurant                     Restaurant   
38                        Portrait Restaurant                           Café   
39                          Vida Vegan Bakery                         Bakery   
40                         Luytens Restaurant                     Restaurant   
41                          Mudmee Restaurant                Thai Restaurant   
42                     Shad Indian Restaurant              Indian Restaurant   
43                              Ev Restaurant             Turkish Restaurant   
44                    Truly Indian Restaurant              Indian Restaurant   
45                 Brothers Cafe & Restaurant      Middle Eastern Restaurant   
46                         Terrace Restaurant                           Café   
47                   Sapori Café & Restaurant                           Café   
48           Le Restaurant de PAUL - Tower 42              French Restaurant   
49                    Muhib Indian Restau

#### It can be clealry seen that the dataframe entails several types of restaurants including: Turkish Restaurant, Steakhouse, English Restaurant, pub etc. These restaurants might serve vegan foods. But for fair comparison the dataframe shall be flittered to entail only categories of Vegetarian / Vegan Restaurant.

In [62]:
# Flitter the dataframe to obtain only categories of Vegetarian / Vegan Restaurant

dataframe_filtered = dataframe_filtered.loc[dataframe_filtered['categories'] == 'Vegetarian / Vegan Restaurant'].reset_index()
dataframe_filtered

index                       name                     categories  \
0      0  Vegan Burgers by Mooshies  Vegetarian / Vegan Restaurant   
1      4                  Vegan Yes  Vegetarian / Vegan Restaurant   
2     15            Essential Vegan  Vegetarian / Vegan Restaurant   
3     18    Vegan No Blood No Bones  Vegetarian / Vegan Restaurant   
4     19     Vegan Veggie Love Cafe  Vegetarian / Vegan Restaurant   
5     23        Vegan Nights London  Vegetarian / Vegan Restaurant   
6     31         Jakes Vegan Steaks  Vegetarian / Vegan Restaurant   

             address  cc    city         country crossStreet  distance  \
0       104 Brick Ln  GB  London  United Kingdom         NaN      1473   
1        64 Brick Ln  GB  London  United Kingdom         NaN      1462   
2   6 Calvert Avenue  GB  London  United Kingdom         NaN      1565   
3                NaN  GB  London  United Kingdom         NaN      1384   
4  29 Corsham Street  GB  London  United Kingdom         NaN      1378   
5                NaN  GB  London  United Kingdom         NaN      1574   
6                NaN  GB  London  United Kingdom         NaN      1585   

                                    formattedAddress  \
0  [104 Brick Ln, London, Greater London, E1 6RL,...   
1  [64 Brick Ln, London, Greater London, E1 6QL, ...   
2  [6 Calvert Avenue, London, Greater London, E2 ...   
3   [London, Greater London, E1 6GY, United Kingdom]   
4  [29 Corsham Street, London, Greater London, N1...   
5       [London, Greater London, E1, United Kingdom]   
6   [London, Greater London, E1 6RU, United Kingdom]   

                                      labeledLatLngs        lat       lng  \
0  [{'lng': -0.07178295871370416, 'label': 'displ...  51.519731 -0.071783   
1  [{'lng': -0.07148288, 'label': 'display', 'lat...  51.518734 -0.071483   
2  [{'lng': -0.07741358, 'label': 'display', 'lat...  51.526356 -0.077414   
3  [{'lng': -0.076607, 'label': 'display', 'lat':...  51.523546 -0.076607   
4  [{'lng': -0.08687138557434082, 'label': 'displ...  51.527583 -0.086871   
5  [{'lng': -0.07140074, 'label': 'display', 'lat...  51.521603 -0.071401   
6  [{'lng': -0.071393, 'label': 'display', 'lat':...  51.521821 -0.071393   

                  neighborhood postalCode           state  \
0                          NaN     E1 6RL  Greater London   
1                          NaN     E1 6QL  Greater London   
2                   Shoreditch     E2 7JP  Greater London   
3                          NaN     E1 6GY  Greater London   
4                          NaN     N1 6DP  Greater London   
5  Spitalfields and Banglatown         E1  Greater London   
6                          NaN     E1 6RU  Greater London   

                         id  
0  5848791af68d8d38cfcf6446  
1  59ada1f8febf314589c6f8d5  
2  557583c1498e61f5350ee6b9  
3  59b189c61acf1175646cdc65  
4  53036500498edf77c3881003  
5  59cd593f91eaca3d8eaa4f52  
6  5a9c0454356b49667bec2e0a

#### Let's visualize vegan restaurants which are avilable within 2.5 km from center of City of London. 

In [63]:
# generate map centred around the City of London center.

venues_map = folium.Map(location=[latitude1, longitude1], zoom_start=13) 

# add a red circle marker to represent center of City of London

folium.features.CircleMarker(
    [latitude1, longitude1],
    radius=10,
    color='red',
    popup='City of London Vegan Restaurant',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add vegan restaurants as blue circle markers

for lat, lng, label in zip(dataframe_filtered.lat, dataframe_filtered.lng, dataframe_filtered.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map


## 2.2 The venue catagory is metro station within 2.5 km radius from City of London.

In [64]:
search_query1 = 'metro station'
radius1 = 2500
print(search_query1 + ' .... OK!')

metro station .... OK!


In [65]:
url1 = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude1, longitude1, VERSION, search_query1, radius1, LIMIT)

In [66]:
results = requests.get(url1).json()
results

{'meta': {'code': 200, 'requestId': '5bd080c74434b940700a3d13'},
 'response': {'venues': [{'categories': [{'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/travel/trainstation_',
       'suffix': '.png'},
      'id': '4bf58dd8d48988d129951735',
      'name': 'Train Station',
      'pluralName': 'Train Stations',
      'primary': True,
      'shortName': 'Train Station'}],
    'hasPerk': False,
    'id': '4af47862f964a520d6f221e3',
    'location': {'address': 'Bishopsgate',
     'cc': 'GB',
     'city': 'London',
     'country': 'United Kingdom',
     'distance': 756,
     'formattedAddress': ['Bishopsgate',
      'London',
      'Greater London',
      'EC2M 7PY',
      'United Kingdom'],
     'lat': 51.51786171849901,
     'lng': -0.08169314799220918,
     'postalCode': 'EC2M 7PY',
     'state': 'Greater London'},
    'name': 'London Liverpool Street Railway Station (LST) (London Liverpool Street Railway Station)',
    'referralId': 'v-1540391112'},
   {'categories': [{'icon

#### Get relevant part of JSON and transform it into a pandas dataframe

In [67]:
# assign relevant part of JSON to venues

venues = results['response']['venues']

# tranform venues into a dataframe

dataframe = json_normalize(venues)
dataframe

categories  hasPerk  \
0   [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
1   [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
2   [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
3   [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
4   [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
5   [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
6   [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
7   [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
8   [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
9   [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
10  [{'id': '4bf58dd8d48988d118951735', 'shortName...    False   
11  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
12  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
13  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
14  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
15  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
16  [{'id': '4bf58dd8d48988d118951735', 'shortName...    False   
17  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
18  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
19  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
20  [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
21  [{'id': '4bf58dd8d48988d118951735', 'shortName...    False   
22  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
23  [{'id': '4deefb944765f83613cdba6e', 'shortName...    False   
24  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
25  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
26  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
27  [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
28  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
29  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
30  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
31  [{'id': '4bf58dd8d48988d118951735', 'shortName...    False   
32  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
33  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
34  [{'id': '4bf58dd8d48988d1fc931735', 'shortName...    False   
35  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
36  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
37  [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
38  [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
39  [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
40  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
41  [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
42  [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
43  [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
44  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
45  [{'id': '4bf58dd8d48988d118951735', 'shortName...    False   
46  [{'id': '4bf58dd8d48988d129951735', 'shortName...    False   
47  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
48  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   
49  [{'id': '4bf58dd8d48988d1fd931735', 'shortName...    False   

                          id       location.address location.cc  \
0   4af47862f964a520d6f221e3            Bishopsgate          GB   
1   4acd8e7df964a52044cc20e3       Station Approach          GB   
2   4ac643b6f964a52072b320e3                City Rd          GB   
3   4ac518f7f964a520c6af20e3             Pancras Rd          GB   
4   4acee9a4f964a5200ed220e3       Station Approach          GB   
5   4acee225f964a52002d220e3              Cannon St          GB   
6   4ad0cba7f964a520ded920e3             Princes St          GB   
7   5036b36bcc6417d4bcd9a1d5           Cranbourn St          GB   
8   4ace1db2f964a5207fce20e3      Queen Victoria St          GB   
9   4a

#### Define information of interest and filter dataframe

In [68]:
# keep only columns that include venue name, and anything that is associated with location

filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue

def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row

dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term

dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

name          categories  \
0   London Liverpool Street Railway Station (LST) ...       Train Station   
1   London Waterloo Railway Station (WAT) (London ...       Train Station   
2                    Angel London Underground Station       Metro Station   
3   London St Pancras International Railway Statio...       Train Station   
4   London Bridge Railway Station (LBG) (London Br...       Train Station   
5                 Cannon Street Railway Station (CST)       Train Station   
6             Bank London Underground and DLR Station       Metro Station   
7         Leicester Square London Underground Station       Metro Station   
8            London Blackfriars Railway Station (BFR)       Train Station   
9   London King's Cross Railway Station (KGX) (Lon...       Train Station   
10                                        Tesco Metro       Grocery Store   
11           London Bridge London Underground Station       Metro Station   
12                Waterloo London Underground Station       Metro Station   
13                Barbican London Underground Station       Metro Station   
14             Blackfriars London Underground Station       Metro Station   
15  King's Cross St. Pancras London Underground St...       Metro Station   
16                                        Tesco Metro       Grocery Store   
17                Monument London Underground Station       Metro Station   
18              Tower Hill London Underground Station       Metro Station   
19              Old Street London Underground Station       Metro Station   
20   Shoreditch High Street London Overground Station       Train Station   
21                                        Tesco Metro       Grocery Store   
22             Westminster London Underground Station       Metro Station   
23         Kings Cross Metropolitan Station (Disused)       Historic Site   
24              St. Paul's London Underground Station       Metro Station   
25                Moorgate London Underground Station       Metro Station   
26                 Holborn London Underground Station       Metro Station   
27         Highbury & Islington Railway Station (HHY)       Train Station   
28               Southwark London Underground Station       Metro Station   
29        Liverpool Street London Underground Station       Metro Station   
30            Aldgate East London Underground Station       Metro Station   
31                                        Tesco Metro       Grocery Store   
32  Whitechapel London Underground and London Over...       Metro Station   
33           Chancery Lane London Underground Station       Metro Station   
34                          Tower Gateway DLR Station  Light Rail Station   
35                  Temple London Underground Station       Metro Station   
36           Mansion House London Underground Station       Metro Station   
37      London Fenchurch Street Railway Station (FST)       Train Station   
38              City Thameslink Railway Station (CTK)       Train Station   
39  Charing Cross Railway Station (CHX) (Charing C...       Train Station   
40                 Aldgate London Underground Station       Metro Station   
41                     Moorgate Railway Station (MOG)       Train Station   
42         London Waterloo East Railway Station (WAE)       Train Station   
43                   Farringdon Railway Station (ZFD)       Train Station   
44              Farringdon London Underground Station       Metro Station   
45                                        Tesco Metro       Grocery Store   
46                   Hoxton London Overground Station       Train Station   
47       Elephant & Castle London Underground Station       Metro Station   
48           Cannon Street London Underground Station       Metro Station   
49                 Borough London Underground Station       Metro Station   

                  address  cc            city         country  \
0             Bishopsgate  GB          London  United Ki

#### It is apparently seen that the dataframe entail irrelevant list such as Tesco Metro and Historic Site. This lists shall be removed from the dataframe.

In [69]:
# Flitter the dataframe to obtain only categories of metro stations

dataframe_filtered = dataframe_filtered.loc[dataframe_filtered['categories'].isin(['Metro Station','Train Station','Light Rail Station']) ].reset_index()
dataframe_filtered

index                                               name  \
0       0  London Liverpool Street Railway Station (LST) ...   
1       1  London Waterloo Railway Station (WAT) (London ...   
2       2                   Angel London Underground Station   
3       3  London St Pancras International Railway Statio...   
4       4  London Bridge Railway Station (LBG) (London Br...   
5       5                Cannon Street Railway Station (CST)   
6       6            Bank London Underground and DLR Station   
7       7        Leicester Square London Underground Station   
8       8           London Blackfriars Railway Station (BFR)   
9       9  London King's Cross Railway Station (KGX) (Lon...   
10     11           London Bridge London Underground Station   
11     12                Waterloo London Underground Station   
12     13                Barbican London Underground Station   
13     14             Blackfriars London Underground Station   
14     15  King's Cross St. Pancras London Underground St...   
15     17                Monument London Underground Station   
16     18              Tower Hill London Underground Station   
17     19              Old Street London Underground Station   
18     20   Shoreditch High Street London Overground Station   
19     22             Westminster London Underground Station   
20     24              St. Paul's London Underground Station   
21     25                Moorgate London Underground Station   
22     26                 Holborn London Underground Station   
23     27         Highbury & Islington Railway Station (HHY)   
24     28               Southwark London Underground Station   
25     29        Liverpool Street London Underground Station   
26     30            Aldgate East London Underground Station   
27     32  Whitechapel London Underground and London Over...   
28     33           Chancery Lane London Underground Station   
29     34                          Tower Gateway DLR Station   
30     35                  Temple London Underground Station   
31     36           Mansion House London Underground Station   
32     37      London Fenchurch Street Railway Station (FST)   
33     38              City Thameslink Railway Station (CTK)   
34     39  Charing Cross Railway Station (CHX) (Charing C...   
35     40                 Aldgate London Underground Station   
36     41                     Moorgate Railway Station (MOG)   
37     42         London Waterloo East Railway Station (WAE)   
38     43                   Farringdon Railway Station (ZFD)   
39     44              Farringdon London Underground Station   
40     46                   Hoxton London Overground Station   
41     47       Elephant & Castle London Underground Station   
42     48           Cannon Street London Underground Station   
43     49                 Borough London Underground Station   

            categories                address  cc            city  \
0        Train Station            Bishopsgate  GB          London   
1        Train Station       Station Approach  GB      South Bank   
2        Metro Station                City Rd  GB       Islington   
3        Train Station             Pancras Rd  GB          London   
4        Train Station       Station Approach  GB          London   
5        Train Station              Cannon St  GB          London   
6        Metro Station             Princes St  GB          London   
7        Metro Station           Cranbourn St  GB          London   
8        Train Station      Queen Victoria St  GB     Blackfriars   
9        Train Station              Euston Rd  GB          London   
10       Metro Station    21 Duke Street Hill  GB          London   
11       Metro Station                York Rd  GB          London   
12       Metro Station          Aldersgate St  GB          London   
13       Metro Station  179 Queen Victoria St  GB          London   
14       Metro Station              Euston Rd  GB          London   
15       Metro Stat

#### Let's visualize metro stations which are avilable within 2.5 km from center of City of London. 

In [70]:
# generate map centred around the City of London center.

venues_map = folium.Map(location=[latitude1, longitude1], zoom_start=13) 

# add a red circle marker to represent center of City of London

folium.features.CircleMarker(
    [latitude1, longitude1],
    radius=10,
    color='red',
    popup='City of London Metro Station',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add metro stations as blue circle markers

for lat, lng, label in zip(dataframe_filtered.lat, dataframe_filtered.lng, dataframe_filtered.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map


## 2.3 The venue catagory is bike rental service within 2.5 km radius from City of London.

In [71]:
search_query1 = 'Bike rental'
radius1 = 2500
print(search_query1 + ' .... OK!')

Bike rental .... OK!


In [72]:
url1 = 'https://api.foursquare.com/v2/venues/search?client_id={}&client_secret={}&ll={},{}&v={}&query={}&radius={}&limit={}'.format(CLIENT_ID, CLIENT_SECRET, latitude1, longitude1, VERSION, search_query1, radius1, LIMIT)

In [73]:
results = requests.get(url1).json()
results

{'meta': {'code': 200, 'requestId': '5bd080c94c1f67197c9d6a84'},
 'response': {'venues': [{'categories': [{'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/food/cafe_',
       'suffix': '.png'},
      'id': '4bf58dd8d48988d16d941735',
      'name': 'Café',
      'pluralName': 'Cafés',
      'primary': True,
      'shortName': 'Café'}],
    'hasPerk': False,
    'id': '56372298498eccf54c9b7aef',
    'location': {'address': '384 Old St',
     'cc': 'GB',
     'city': 'London',
     'country': 'United Kingdom',
     'distance': 1588,
     'formattedAddress': ['384 Old St',
      'London',
      'Greater London',
      'EC1V 9LT',
      'United Kingdom'],
     'labeledLatLngs': [{'label': 'display',
       'lat': 51.52716467475097,
       'lng': -0.0785338000638642}],
     'lat': 51.52716467475097,
     'lng': -0.0785338000638642,
     'neighborhood': 'Shoreditch',
     'postalCode': 'EC1V 9LT',
     'state': 'Greater London'},
    'name': 'The Bike Shed',
    'referralId': 'v-15

#### Get relevant part of JSON and transform it into a pandas dataframe

In [74]:
# assign relevant part of JSON to venues

venues = results['response']['venues']

# tranform venues into a dataframe

dataframe = json_normalize(venues)
dataframe

categories  hasPerk  \
0   [{'id': '4bf58dd8d48988d16d941735', 'shortName...    False   
1   [{'id': '4e4c9077bd41f78e849722f9', 'shortName...    False   
2   [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   
3   [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   
4   [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   
5   [{'id': '4bf58dd8d48988d106941735', 'shortName...    False   
6   [{'id': '4c38df4de52ce0d596b336e1', 'shortName...    False   
7   [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   
8   [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   
9   [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   
10  [{'id': '4e4c9077bd41f78e849722f9', 'shortName...    False   
11  [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   
12  [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   
13  [{'id': '4bf58dd8d48988d124951735', 'shortName...    False   
14  [{'id': '4e4c9077bd41f78e849722f9', 'shortName...    False   
15  [{'id': '4f04afc02fb6e1c99f3db0bc', 'shortName...    False   
16  [{'id': '4f04afc02fb6e1c99f3db0bc', 'shortName...    False   
17  [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   
18  [{'id': '4bf58dd8d48988d1f6931735', 'shortName...    False   
19  [{'id': '4bf58dd8d48988d1ef941735', 'shortName...    False   
20  [{'id': '4bf58dd8d48988d1ae941735', 'shortName...    False   
21  [{'id': '4e4c9077bd41f78e849722f9', 'shortName...    False   
22  [{'id': '4bf58dd8d48988d126941735', 'shortName...    False   
23  [{'id': '4bf58dd8d48988d1ef941735', 'shortName...    False   
24  [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   
25  [{'id': '4f04b08c2fb6e1c99f3db0bd', 'shortName...    False   
26  [{'id': '4c38df4de52ce0d596b336e1', 'shortName...    False   
27  [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   
28  [{'id': '4bf58dd8d48988d1ef941735', 'shortName...    False   
29  [{'id': '4e4c9077bd41f78e849722f9', 'shortName...    False   
30  [{'id': '4bf58dd8d48988d1f6931735', 'shortName...    False   
31  [{'id': '4bf58dd8d48988d10f941735', 'shortName...    False   
32  [{'id': '4e4c9077bd41f78e849722f9', 'shortName...    False   
33  [{'id': '4e4c9077bd41f78e849722f9', 'shortName...    False   
34  [{'id': '4bf58dd8d48988d1ef941735', 'shortName...    False   
35  [{'id': '4bf58dd8d48988d1ef941735', 'shortName...    False   
36                                                 []    False   
37  [{'id': '4bf58dd8d48988d1ef941735', 'shortName...    False   
38  [{'id': '4bf58dd8d48988d1ef941735', 'shortName...    False   
39  [{'id': '5032833091d4c4b30a586d60', 'shortName...    False   
40  [{'id': '5032833091d4c4b30a586d60', 'shortName...    False   
41  [{'id': '4e4c9077bd41f78e849722f9', 'shortName...    False   
42  [{'id': '5032833091d4c4b30a586d60', 'shortName...    False   
43  [{'id': '4bf58dd8d48988d1ef941735', 'shortName...    False   
44  [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   
45  [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   
46  [{'id': '4bf58dd8d48988d1ef941735', 'shortName...    False   
47  [{'id': '4e4c9077bd41f78e849722f9', 'shortName...    False   
48  [{'id': '4bf58dd8d48988d1ef941735', 'shortName...    False   
49  [{'id': '4bf58dd8d48988d115951735', 'shortName...    False   

                          id                               location.address  \
0   56372298498eccf54c9b7aef                                     384 Old St   
1   5153ef77582ff7cb43bb617a                     The Vaults, Montague Close   
2   5492c394498ee0902b1494a3                           97 Tower Bridge Road   
3   526914d611d27428df6e2a80                                            NaN   
4   4f86f805e4b027051155977f                   138-140 Cambridge Heath Road   
5   4b9e939ef964a520b1f036e3                                            NaN   
6   4e149a08ae60fe00dfe0aa40                         Banyard House Car Park   
7   4c9de69754c8a1cd7af5874b                

#### Define information of interest and filter dataframe

In [75]:
# keep only columns that include venue name, and anything that is associated with location

filtered_columns = ['name', 'categories'] + [col for col in dataframe.columns if col.startswith('location.')] + ['id']
dataframe_filtered = dataframe.loc[:, filtered_columns]

# function that extracts the category of the venue

def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

# filter the category for each row

dataframe_filtered['categories'] = dataframe_filtered.apply(get_category_type, axis=1)

# clean column names by keeping only last term

dataframe_filtered.columns = [column.split('.')[-1] for column in dataframe_filtered.columns]

dataframe_filtered

name                categories  \
0                                   The Bike Shed                      Café   
1                    On Your Bike - London Bridge  Bike Rental / Bike Share   
2      Machine Cycling Café/Bike Shop and Repairs                 Bike Shop   
3            Bike Parking Island, Waterloo Bridge                 Bike Shop   
4                                       Bikeworks                 Bike Shop   
5                                   The Bike Shed                     Track   
6                                  City Bike Pump                   Parking   
7                                  Bike Yard East                 Bike Shop   
8                                         Bikefix                 Bike Shop   
9                                       tokyobike                 Bike Shop   
10                       TfL Santander Cycle Hire  Bike Rental / Bike Share   
11                               Brick Lane Bikes                 Bike Shop   
12                            Electric Bike Store                 Bike Shop   
13                              City Bike Service           Automotive Shop   
14                       TfL Santander Cycle Hire  Bike Rental / Bike Share   
15                                   iPads Rental         Mobile Phone Shop   
16                                   iPads Rental         Mobile Phone Shop   
17                                     14 Bike Co                 Bike Shop   
18  Trinity Square Flat -  London Vacation Rental            General Travel   
19                               RENTAL CAR GROUP       Rental Car Location   
20                   City University Bike Storage                University   
21                       TfL Santander Cycle Hire  Bike Rental / Bike Share   
22                    Southwark Council Bike Shed       Government Building   
23  Carrentalchoice - Stansted Airport Car Rental       Rental Car Location   
24                                 Free Bike Pump                 Bike Shop   
25                          Brake Away Bike Tours             Travel Agency   
26                                  TCS Bike Shed                   Parking   
27                                 About The Bike                 Bike Shop   
28                                Avis Car Rental       Rental Car Location   
29                       TfL Santander Cycle Hire  Bike Rental / Bike Share   
30                   StayHomeAway Vacation Rental            General Travel   
31                             Rusty Bike Kitchen         Indian Restaurant   
32                              Baja Bikes London  Bike Rental / Bike Share   
33                       TfL Santander Cycle Hire  Bike Rental / Bike Share   
34                                Avis Car Rental       Rental Car Location   
35                                sixt car rental       Rental Car Location   
36                        Easy London Rentals Ltd                      None   
37                            National Car Rental       Rental Car Location   
38                                        Thrifty       Rental Car Location   
39                                       BR Bikes           Motorcycle Shop   
40                                Emem Bike Store           Motorcycle Shop   
41                       TfL Santander Cycle Hire  Bike Rental / Bike Share   
42                                      Chas Bike           Motorcycle Shop   
43                                Avis Car Rental       Rental Car Location   
44                                  Graphic Bikes                 Bike Shop   
45                                   Action Bikes                 Bike Shop   
46                                   Alamo Rental       Rental Car Location   
47                       TfL Santander Cycle Hire  Bike Rental / Bike Share   
48                            National Car Rental       Rental Car Location   
49                            London Bike Kitchen                 Bike Shop   

               

#### It can be clealry seen that the dataframe entails unrelated categories such as The Bike Shed Café, Bike Shope and City Bike Pump. Hence, the dataframe shall be flittered to comprise only categories of Bike Rental / Bike Share

In [76]:
# Flitter the dataframe to obtain only categories of metro stations

dataframe_filtered = dataframe_filtered.loc[dataframe_filtered['categories'] == 'Bike Rental / Bike Share'].reset_index()
dataframe_filtered

index                          name                categories  \
0      1  On Your Bike - London Bridge  Bike Rental / Bike Share   
1     10      TfL Santander Cycle Hire  Bike Rental / Bike Share   
2     14      TfL Santander Cycle Hire  Bike Rental / Bike Share   
3     21      TfL Santander Cycle Hire  Bike Rental / Bike Share   
4     29      TfL Santander Cycle Hire  Bike Rental / Bike Share   
5     32             Baja Bikes London  Bike Rental / Bike Share   
6     33      TfL Santander Cycle Hire  Bike Rental / Bike Share   
7     41      TfL Santander Cycle Hire  Bike Rental / Bike Share   
8     47      TfL Santander Cycle Hire  Bike Rental / Bike Share   

                      address  cc           city         country  crossStreet  \
0  The Vaults, Montague Close  GB         London  United Kingdom          NaN   
1                 33 Queen St  GB         London  United Kingdom          NaN   
2               Aldersgate St  GB       Barbican  United Kingdom          NaN   
3              New Globe Walk  GB     Camberwell  United Kingdom      Park St   
4           Clerkenwell Green  GB    Clerkenwell  United Kingdom  Sekforde St   
5           Gabriels Wharf 56  GB         London  United Kingdom          NaN   
6                 Hardwick St  GB    Clerkenwell  United Kingdom          NaN   
7                   Golden Ln  GB       Barbican  United Kingdom          NaN   
8              Wellington Row  GB  Bethnal Green  United Kingdom          NaN   

   distance                                   formattedAddress  \
0      1098  [The Vaults, Montague Close, London, Greater L...   
1       471  [33 Queen St, London, Greater London, EC4R 1QS...   
2       695  [Aldersgate St, Barbican, Greater London, EC1A...   
3       985  [New Globe Walk (Park St), Camberwell, Greater...   
4      1221  [Clerkenwell Green (Sekforde St), Clerkenwell,...   
5      1545  [Gabriels Wharf 56, London, Greater London, SE...   
6      1750  [Hardwick St, Clerkenwell, Greater London, EC1...   
7       662  [Golden Ln, Barbican, Greater London, EC1Y 0SH...   
8      2069  [Wellington Row, Bethnal Green, Greater London...   

                                      labeledLatLngs        lat       lng  \
0  [{'lng': -0.08873991438149605, 'label': 'displ...  51.505963 -0.088740   
1  [{'lng': -0.09301199122900178, 'label': 'displ...  51.511427 -0.093012   
2  [{'lng': -0.09745039826045504, 'label': 'displ...  51.520863 -0.097450   
3  [{'lng': -0.09700159031598998, 'label': 'displ...  51.507333 -0.097002   
4  [{'lng': -0.10479927062988281, 'label': 'displ...  51.523164 -0.104799   
5  [{'lng': -0.10994911193847656, 'label': 'displ...  51.507380 -0.109949   
6  [{'lng': -0.10801792144775389, 'label': 'displ...  51.527783 -0.108018   
7  [{'lng': -0.09433721602122123, 'label': 'displ...  51.521393 -0.094337   
8  [{'lng': -0.06981350758141308, 'label': 'displ...  51.528067 -0.069814   

  neighborhood postalCode           state                        id  
0          NaN    SE1 9DA  Greater London  5153ef77582ff7cb43bb617a  
1          NaN   EC4R 1QS  Greater London  4e148d6188777cd5da34d5bf  
2          NaN   EC1A 4JP  Greater London  4f1e8bf3e4b06f7f31dd9202  
3          NaN    SE1 9DT  Greater London  4c56f8bf7329c928abc18d80  
4          NaN   EC1R 0EB  Greater London  4c514387ed8895214ccc47e4  
5          NaN    SE1 9PP  Greater London  4f7ec0080039ef8a138e2b9c  
6          NaN   EC1R 4RB  Greater London  4d9f0fdd47ad3704b5f247e5  
7          NaN   EC1Y 0SH  Greater London  4d07cee2b26ea143a9e4c3e7  
8          NaN     E2 7BD  Greater London  4fe1c51ee4b0518a421a6f08

#### Let's visualize bike rental services which are avilable within 2.5 km from center of City of London. 

In [78]:
# generate map centred around the City of London center.

venues_map = folium.Map(location=[latitude1, longitude1], zoom_start=13) 

# add a red circle marker to represent center of City of London

folium.features.CircleMarker(
    [latitude1, longitude1],
    radius=10,
    color='red',
    popup='City of London Bike Rental',
    fill = True,
    fill_color = 'red',
    fill_opacity = 0.6
).add_to(venues_map)

# add bike rental services as blue circle markers

for lat, lng, label in zip(dataframe_filtered.lat, dataframe_filtered.lng, dataframe_filtered.categories):
    folium.features.CircleMarker(
        [lat, lng],
        radius=5,
        color='blue',
        popup=label,
        fill = True,
        fill_color='blue',
        fill_opacity=0.6
    ).add_to(venues_map)

# display map
venues_map


# Conclusions 

From data segmentation and clustering, it was learned that New York City has five boroughs and Greater London has thirty three boroughs (including City of London). Though Greater London has many boroughs, both cities have almost equal population. From exploration of the geographical location, Greater London has a great number of accesses to public transport. The number of bike rental services within five kilometre diameter from Manhattan city centre is higher than City of London.  The choice for vegan restaurants in City of London is much better than Manhattan. In general, both cities can be considered as eco-friendly cities but City of London is more vegan-friendly than New Your City. 